### ISSUE TITLE
File search always shows up empty

### ISSUE THREAD

**Issue by FraserEmbrey** [patrickf3139/fzf.fish#23]
I have installed fzf, fd and bash. I also have ripgrep installed and I had the jethrokuan plugin but uninstalled with fisher rm before installing this one.

The commands all work except for the search files which always shows up as 0/0. The interface loads but it doesn't have any files to show.

I am using pop!_OS 20.04 and alacritty as my terminal emulator

**Comment by FraserEmbrey** [comment]
Realised fd needs to be aliased to fdfind. Might be worth noting that it only works with fdfind as linked, or making uses it uses the correct fd

**Comment by patrickf3139** [comment]
Hi Fraser! I'm confused. I don't have `fd` aliased to `fdfind`. How did you realize you needed to alias it to `fdfind`?

**Comment by FraserEmbrey** [comment]
> Hi Fraser! I'm confused. I don't have `fd` aliased to `fdfind`. How did you realize you needed to alias it to `fdfind`?

I went to the [fd github page](https://github.com/sharkdp/fd) linked to in your README and read the installation instructions more carefully. The Ubuntu section has a paragraph below the apt command saying:

> Note that the binary is called fdfind as the binary name fd is already used by another package. It is recommended that you add an alias fd=fdfind to your shells initialization file, in order to use fd in the same way as in this documentation.

**Comment by patrickf3139** [comment]
Thanks! I may create an FAQ and add it there.
