### ISSUE TITLE
plugin did not install correctly 

### ISSUE THREAD

**Issue by matthiasdebernardini** [patrickf3139/fzf.fish#27]
I had jethrokuan's fzf installed and that worked fine but this one seemed like it had better features. 

so  I uninstalled 
`fisher rm jethrokuans/fzf`

installed yours 
`fisher add patrickf3139/fzf.fish`

but now nothing works

I'm on ubuntu 18 using the latest version of fish and fisher 

I am somewhat new to fish and have read the docs but maybe I am missing a step?

I tried running both 
set --universal --export FZF_DEFAULT_OPTS --height 50% --margin 1
 set --export FZF_DEFAULT_OPTS --height 50% --margin 1

but that didnt help also fish can find `fzf` in the prompt so I dont think thats it

`fisher ls` shows that its installed and I can see the files in my config folder.

Something must not be sourcing correctly but I can't figure out what, any tips?

**Comment by matthiasdebernardini** [comment]
I think its my fzf installation, because I do have `set PATH ~/.fzf/bin $PATH` in my config.fish 

I will try uninstalling fzf and reinstalling maybe that will help

**Comment by matthiasdebernardini** [comment]
ok so ctrl r now works (which is the most important for me) but ctrl f does not. As in, nothing happens when I press that, same as ctrl v (xsel shows up and complains).

Unsure how to continue.

**Comment by matthiasdebernardini** [comment]
`fd --hidden --follow --color=always --exclude=.git 2> /dev/null | fzf --ansi --preview='__fzf_preview_file {}'` this works just as expected so something before this is not being handled correctly

**Comment by patrickf3139** [comment]
Can you paste the output of `bind | tail -n 20`?

**Comment by matthiasdebernardini** [comment]
Hi yes, 

❯ bind | tail -n 20
bind \cn down-or-search
bind \cf forward-char
bind \cb backward-char
bind \ct fzf-file-widget
bind \et transpose-words
bind \eu upcase-word
bind \ec fzf-cd-widget
bind \e backward-kill-word
bind \eb backward-word
bind \ef forward-word
bind \e\[1\;5C forward-word
bind \e\[1\;5D backward-word
bind \e\< beginning-of-buffer
bind \e\> end-of-buffer
bind \e\[I 'begin;end'
bind \e\[O 'begin;end'
bind \cr fzf-history-widget
bind -M insert \ct fzf-file-widget
bind -M insert \cr fzf-history-widget
bind -M insert \ec fzf-cd-widget

**Comment by matthiasdebernardini** [comment]
I appreciate the help on a friday evening as well.

**Comment by patrickf3139** [comment]
No problem! Thanks for checking out my plugin.

Hmm something is fishy about your bindings.
1. I don't see the bindings that should have been set up by `fzf.fish`.
2. I see bindings for the official fzf shell integraion (see https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish). e.g. `fzf-file-widget`, and `fzf-history-widget`, `fzf-cd-widget` are all functions defined in the file I just linked.

Try uninstall the official widget? That'll solve problem 2 but something seems to be preventing `fzf.fish` configuration from being executed. Not sure. After you uninstall the official widget, can you paste the full output of `bind`, please?

**Comment by matthiasdebernardini** [comment]
no problem, 

well turns out I was using the old fish (2.7) version and while trying to upgrade to the newest fish, I locked myself out of my computer... the authentication on my OS stopped working.

I think using the latest version of fish and doing a clean install (instead of switching around from different implementations of fzf fish integration) will solve the problem. 

I think the switching around caused them to step all over each other, which is why it's not working.

I will try that and get back.

**Comment by patrickf3139** [comment]
Ah yes, an emphasis of mine when writing this plugin was to not rely on external utilities as much as possible, and so that meant using the latest and greatest fish features. So I am not sure but I don't think it works with fish 2.7. Let me add that to the README.

Good luck getting back onto your laptop! Yes, please get back to me and if things work please close this issue.
Btw, would you mind giving this repo a star if it works for you?

**Comment by matthiasdebernardini** [comment]
Of course. 

BTW how do you recommend I install fzf?

I can install it using vim-plug (neovim plugin manager), or from source. How do you usually do it?

**Comment by patrickf3139** [comment]
Sorry, not sure how to help you. I am only experienced with macOS. All I know is that for macOS, I recommend using brew. And if you are using Ubuntu or another distro that uses apt, you'll need to alias fdfind to fd. See #23 for why. Anything else I dunno...

**Comment by matthiasdebernardini** [comment]
no problem, it was the old version everything is working exactly as I intended!

thanks for the help!

BTW you should add an example for using Ctrl F in the shell to find a file and open it with vim, I think people will like that.
