### ISSUE TITLE
fzf preview and keybind not working on MacOS

### ISSUE THREAD

**Issue by ciscohack** [patrickf3139/fzf.fish#41]
Hi Patrick,

I need your help to address the mentioned problem. I recently installed fish shell and your fzf plugin through fisher but keybinding and preview not working.  getting the following message in the preview window.

![image](https://user-images.githubusercontent.com/11479557/94659587-25a0d200-0322-11eb-8650-c26578af9b98.png)

Re,
Praveen

**Comment by patrickf3139** [comment]
Hi Praveen! It seems you are trying to use it through zsh. fzf.fish is a fish only plugin. Does that make sense?

**Comment by ciscohack** [comment]
@patrickf3139 thanks for a prompt response. no, I am not using it with zsh. I am using this with fish shell only but I think issue started after downloading fzf "keybind.fish" file and source in my config.fish file.

**Comment by patrickf3139** [comment]
There is no `keybind.fish` file in the repo. I'm afraid I don't know what file you are talking about.
If you stop sourcing `keybind.fish` in your config.fish, does the plugin work?

**Comment by ciscohack** [comment]
@patrickf3139  just re-installed everything from scratch and thankfully everything is now working as expected. actually, I sourced keybinding of "https://github.com/junegunn/fzf"

**Comment by patrickf3139** [comment]
Woohoo great to hear it works! 👍 

`set --universal fzf_fish_custom_keybindings` is only needed if you want to customize the key bindings. If you don't mind the default key bindings, then don't set it

**Comment by ciscohack** [comment]
Thanks @patrickf3139

**Comment by patrickf3139** [comment]
You're very welcome :)
