### ISSUE TITLE
How to ignore directories?

### ISSUE THREAD

**Issue by gnur** [patrickf3139/fzf.fish#42]
I use fzf to jump around to my code repos all over my home dir, but I never have to search within the .cache dir or within node_modules, is there a way to exclude to make fd respond a bit faster?

**Comment by patrickf3139** [comment]
Hi @gnur, yes, please see the bottom of https://github.com/sharkdp/fd#excluding-specific-files-or-directories.

**Comment by gnur** [comment]
But how does that relate to an option for fzf.fish ? I cannot find any config that addresses the default fd command? Or do I just have to change the original code?

**Comment by patrickf3139** [comment]
You read

> If you want fd to ignore these patterns globally, you can put them in fd's global ignore file. This is usually located in ~/.config/fd/ignore in macOS or Linux, and %APPDATA%\fd\ignore in Windows.

right?

> But how does that relate to an option for fzf.fish ?

It doesn't. Making the ignore file affects the fd command on every invocation of it even outside of fzf.fish.
