### ISSUE TITLE
Can we use skim instead of fzf?

### ISSUE THREAD

**Issue by PopeRigby** [patrickf3139/fzf.fish#57]
It seems that [skim](https://github.com/lotabout/skim) is pretty much a drop in replacement for fzf. Would it be possible to use this instead?

**Comment by patrickf3139** [comment]
Hi @PopeRigby, why do you prefer skim over fzf?

**Comment by PopeRigby** [comment]
Personally, because it's written in Rust, so I'm able to contribute to it. I also already use skim instead, so I'd rather not install fzf just for this. 

I'm not saying you should necessarily replace fzf with skim in this script, just that the script should maybe check if skim is installed and use it instead if fzf isn't. 

I've done some testing, and aliasing fzf to skim works perfectly fine, but the above method would be preferable, because I think using an alias is a bit hacky.

**Comment by patrickf3139** [comment]
Hi again,
Thanks for explaining. That makes a lot of sense for your situation. Being able to understand the source code is indeed very valuable and if I were in your shoes, I would also choose to use skim over fzf.
However, 
- I think you use case is very very rare. fzf is by far way more popular than skim (fzf has 15x more stars and is way Google search for "fzf fuzzy finder" returns way more helpful results than "skim fuzzy finder").
- It wouldn't be an unreasonable amount of work for me to fallback to skim if fzf is not installed. However, that is still a decent amount of code I need to maintain and test with every new version of fzf.fish. I do this in my spare time and so making it harder for me to develop my plugin is a net negative for everyone.
- Furthermore, there is no guarantee that skim is always going to be a drop-in replacement for fzf. Either library could diverge from the other.

So in light of all that, I hope you can understand my decision to make my plugin only work with fzf. I recommend continuing to use the alias. It does feel hacky but I can't think of use cases where it'll be an issue.

**Comment by PopeRigby** [comment]
Ok, fair enough. Thank you for your time, and the plugin :slightly_smiling_face:
